### ISSUE TITLE
chore: convert all services to proto

### ISSUE THREAD

**Issue by Anmol1696** [Anmol1696/starship#31]
## Overview
A grpc service is able to host both rest and grpc services.
If we convert all the service to grpcs we will have a clean interfaces by there protos which we can store in the root dir.

### Cons
Currently for all the API services, have been built using a custom go-chi template and structure. A grpc service would need modification to the template

### Pros
What a service does will become explicit with protos. Grpc + rest service will be a better paradigm then just rest service

**Comment by Anmol1696** [comment]
:smile:

**Comment by pyramation** [comment]
hehe sorry that was an accident :)

**Comment by Anmol1696** [comment]
Both exposer #36 and chain registry #38 have been converted to porto gprc. Closing the issue
